package br.com.ifba.exerciciocrud.view;

import br.com.ifba.exerciciocrud.entities.Tarefa;
import br.com.ifba.exerciciocrud.service.FacadeInstance;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author curso
 */
public class TelaTarefas extends javax.swing.JFrame {

    /**
     * Creates new form TelaTarefas
     */
    public TelaTarefas() {
        initComponents();

        // Chama método para atualizar tabela com base no banco de dados.
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPainel = new javax.swing.JPanel();
        lblHomescreen = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnCriarTarefa = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarefas = new javax.swing.JTable();
        lblPesquisaImg = new javax.swing.JLabel();
        lblHomescreenImg = new javax.swing.JLabel();
        lblEspaco1 = new javax.swing.JLabel();
        lblEspaco2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlPainel.setBackground(new java.awt.Color(0, 0, 0));
        pnlPainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomescreen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHomescreen.setForeground(new java.awt.Color(204, 204, 204));
        lblHomescreen.setText("Homescreen");
        pnlPainel.add(lblHomescreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 140, 30));

        txtPesquisa.setBackground(new java.awt.Color(18, 42, 61));
        txtPesquisa.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        txtPesquisa.setText("Procurar...");
        txtPesquisa.setToolTipText("Digite aqui um nome de tarefa para pesquisar.");
        txtPesquisa.setBorder(null);
        txtPesquisa.setOpaque(true);
        txtPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisaMouseClicked(evt);
            }
        });
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        pnlPainel.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, 30));

        btnCriarTarefa.setBackground(new java.awt.Color(12, 27, 39));
        btnCriarTarefa.setForeground(new java.awt.Color(204, 204, 204));
        btnCriarTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/exerciciocrud/images/plus-icon.png"))); // NOI18N
        btnCriarTarefa.setText(" Criar tarefa");
        btnCriarTarefa.setToolTipText("Cria nova tarefa");
        btnCriarTarefa.setBorder(null);
        btnCriarTarefa.setBorderPainted(false);
        btnCriarTarefa.setOpaque(true);
        btnCriarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarTarefaActionPerformed(evt);
            }
        });
        pnlPainel.add(btnCriarTarefa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 110, 30));

        btnRemover.setBackground(new java.awt.Color(153, 0, 0));
        btnRemover.setForeground(new java.awt.Color(204, 204, 204));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        pnlPainel.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 90, 40));

        btnEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlPainel.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 90, 40));

        tblTarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTarefas.setForeground(new java.awt.Color(0, 0, 0));
        tblTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade", "Descrição", "Fornecedor"
            }
        ));
        tblTarefas.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tblTarefas);

        pnlPainel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 700, 384));

        lblPesquisaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/exerciciocrud/images/field-search.png"))); // NOI18N
        pnlPainel.add(lblPesquisaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblHomescreenImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/exerciciocrud/images/field-homescreen.png"))); // NOI18N
        pnlPainel.add(lblHomescreenImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));
        pnlPainel.add(lblEspaco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 20, 380));
        pnlPainel.add(lblEspaco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 700, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTarefaActionPerformed

        // Exibe tela de criar tarefas
        new TelaCriarTarefa().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnCriarTarefaActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed

        // Instanciando string para pesquisa
        String pesquisa = txtPesquisa.getText();

        // Criando tabela com modelo já existente
        DefaultTableModel tab = (DefaultTableModel) tblTarefas.getModel();
        
        // Armazenando em lista de tarefas o retorno da pesquisa
        List<Tarefa> resultado = FacadeInstance.getInstance().buscarTarefa(pesquisa);
        
        // Zera a tabela para exibir depois somente os resultados da pesquisa.
        tab.setRowCount(0);
        
        // Vai colocando os itens encontrados na tabela nova
        for(Tarefa tar: resultado) {
            tab.addRow(new Object[]{
                tar.getNome(),
                tar.getQuantidade(),
                tar.getDescricao(),
                tar.getFornecedor()});
        }

        // Seta o novo modelo da tabela
        tblTarefas.setModel(tab);

    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaMouseClicked

        // Limpa o campo de pesquisa quando clicado
        txtPesquisa.setText("");

    }//GEN-LAST:event_txtPesquisaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        // Obtendo linha selecionada e gravando na variável.
        long linha = tblTarefas.getSelectedRow();

        if (linha == -1) {
            
            // Exibe mensagem de erro
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecione uma linha da tabela.");
            
        } else {
            
            // Obtendo nome do item a ser editado
            String editar = (String) tblTarefas.getModel().getValueAt((int) linha, 0);
            
            // Buscando a tarefa no banco de dados
            List<Tarefa> tarefas = FacadeInstance.getInstance().buscarTarefa(editar);
            
            // Pega a tarefa encontrada pelo nome no índice zero...
            // ... já que o programa não aceita duas tarefas de mesmo nome
            Tarefa encontrada = tarefas.get(0);
            
            // Exibindo tela de edição de item, com os dados da tarefa
            new TelaEditarTarefa(encontrada);
            
            // Ocultando tela atual
            this.setVisible(false);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        // Obtendo linha selecionada e gravando na variável.
        long linha = tblTarefas.getSelectedRow();

        if (linha == -1) {
            
            // Exibe mensagem de erro
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecione uma linha da tabela.");
            
        // Só dá continuidade à remoção se o usuário confirmar.
        } else if(JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja excluir?") == 0) {
            
            // Obtendo nome do item a ser excluído
            String remover = (String) tblTarefas.getModel().getValueAt((int) linha, 0);
            
            // Buscando item pelo nome no banco de dados
            List<Tarefa> resultado = FacadeInstance.getInstance().buscarTarefa(remover);
            
            // Apagando item encontrado do banco de dados
            FacadeInstance.getInstance().removerTarefa(resultado.get(0));
            
            // Ocultando tela principal
            this.setVisible(false);
            
            // Exibindo mensagem de sucesso
            JOptionPane.showMessageDialog(rootPane, "Item excluído com sucesso!");
            
            // Exibindo tela principal novamente
            new TelaTarefas().setVisible(true);
            
        } else {
            
            JOptionPane.showMessageDialog(rootPane, "Exclusão cancelada pelo usuário." +
                    "\nOs dados não foram alterados.");
            
        }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    public void atualizarTabela() {

        // Obtendo modelo da tabela usada
        DefaultTableModel tab = (DefaultTableModel) tblTarefas.getModel();
        
        // Cria uma lista com os itens do banco de dados
        List<Tarefa> tar = FacadeInstance.getInstance().encontrarTodasTarefas();

        // Percorre a lista adicionando seus itens à tabela
        for (Tarefa item : tar) {
            tab.addRow(new Object[]{
                item.getNome(),
                item.getQuantidade(),
                item.getDescricao(),
                item.getFornecedor()});
        }

        // Seta o modelo atualizado
        tblTarefas.setModel(tab);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTarefas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarTarefa;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEspaco1;
    private javax.swing.JLabel lblEspaco2;
    private javax.swing.JLabel lblHomescreen;
    private javax.swing.JLabel lblHomescreenImg;
    private javax.swing.JLabel lblPesquisaImg;
    private javax.swing.JPanel pnlPainel;
    private javax.swing.JTable tblTarefas;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
