/**
 *
 * @author Lucas Bastos
 */
public class Genio extends javax.swing.JFrame {

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagem = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        lblInfo = new javax.swing.JLabel();
        lblTextoBalao = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genie.png"))); // NOI18N
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        spnValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 80, 30));

        lblInfo.setText("Valor:");
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        lblTextoBalao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTextoBalao.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoBalao.setText("<html>Vou pensar em um número entre 1 e 5. Tente adivinhar!</html>");
        getContentPane().add(lblTextoBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, 60));

        lblBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baloon.png"))); // NOI18N
        getContentPane().add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnPalpite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        double num = 1 + Math.random() * (6-1);
        int numeroGenio = (int) num;
        int numeroUsuario = Integer.parseInt(spnValor.getValue().toString());
        
        if (numeroGenio == numeroUsuario)
            lblTextoBalao.setText("<html>Você acertou!</html>");
        else
            lblTextoBalao.setText("<html>Você errou! Eu pensei em " + numeroGenio + "</html>");
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTextoBalao;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
