package exerciciobanco;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Bastos
 */
public class ExercicioBanco extends javax.swing.JFrame {

    // Instanciando novo objeto banco:
    Banco p1 = new Banco();
    
    public ExercicioBanco() {
        initComponents();
        // Desativando inicialmente botões que precisam de conta.
        btnInfo.setEnabled(false);
        btnDeposito.setEnabled(false);
        btnSaque.setEnabled(false);
        btnPagarMensalidade.setEnabled(false);
        btnEncerrarConta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        sprLinha = new javax.swing.JSeparator();
        lblMensagem = new javax.swing.JLabel();
        btnCriarConta = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnSaque = new javax.swing.JButton();
        btnEncerrarConta = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        btnPagarMensalidade = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Banco POO");

        lblMensagem.setText("Seja bem-vindo!");

        btnCriarConta.setText("Criar minha conta");
        btnCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarContaActionPerformed(evt);
            }
        });

        btnInfo.setText("Verificar info/saldo");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnDeposito.setText("Realizar depósito");
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });

        btnSaque.setText("Realizar saque");
        btnSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaqueActionPerformed(evt);
            }
        });

        btnEncerrarConta.setText("Encerrar conta");
        btnEncerrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarContaActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(102, 51, 0));
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair do programa");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblNomeCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnPagarMensalidade.setText("Pagar taxa/mês");
        btnPagarMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMensalidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(sprLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblMensagem)
                        .addGap(214, 214, 214)
                        .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnPagarMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnInfo)
                        .addGap(20, 20, 20)
                        .addComponent(btnSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnEncerrarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(sprLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncerrarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaqueActionPerformed
        // TODO add your handling code here:
        // Variável para valor do saque:
        float valor;
        
        // Pedindo valor do saque para usuário:
        valor = Float.parseFloat(JOptionPane.showInputDialog(null, "Insira o valor do saque:"));
        
        // Sacando valor da conta:
        p1.sacar(valor);
    }//GEN-LAST:event_btnSaqueActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        // TODO add your handling code here:
        // Variável para valor do depósito:
        float valor;
        
        // Pedindo valor do depósito para usuário:
        valor = Float.parseFloat(JOptionPane.showInputDialog(null, "Insira o valor do depósito:"));
        
        // Depositando valor na conta:
        p1.depositar(valor);
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaActionPerformed
        // TODO add your handling code here:
        // Strings para nome do cliente e tipo de conta:
        String nomeCliente = new String();
        String tipoConta = new String();
        
        // Pedindo tipo de conta para usuário, podendo ser apenas CC ou CP:
        do {
            tipoConta = JOptionPane.showInputDialog(null, "Insira o tipo de conta (CC ou CP):");
            if(!tipoConta.equals("CC") && !tipoConta.equals("CP")) {
                JOptionPane.showMessageDialog(null, "Por favor, insira uma opção válida!");
            }
        } while (!tipoConta.equals("CC") && !tipoConta.equals("CP"));
        
        // Criando conta:
        p1.abrirConta(tipoConta);
        
        // Pedindo nome para usuário:
        nomeCliente = JOptionPane.showInputDialog(null, "Insira o seu nome:");
        p1.setNomeCliente(nomeCliente);
        
        // Exibindo mensagem de sucesso:
        JOptionPane.showMessageDialog(null, "Conta criada com sucesso!");
        
        // Desativando botão de criar conta:
        btnCriarConta.setEnabled(false);
        
        // Exibindo nome do cliente no label respectivo:
        lblNomeCliente.setText("Usuário: " + nomeCliente);
        
        // Exibindo icone no label de imagem:
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconepessoa.png")));
        
        // Ativando botões de operações bancárias:
        btnInfo.setEnabled(true);
        btnDeposito.setEnabled(true);
        btnSaque.setEnabled(true);
        btnPagarMensalidade.setEnabled(true);
        btnEncerrarConta.setEnabled(true);
    }//GEN-LAST:event_btnCriarContaActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        String dados = new String();
        // Escrevendo dados na string:
        dados = "* Dados do cliente *" +
                "\nTipo de conta: " + p1.getTipoConta() +
                "\nNome: " + p1.getNomeCliente() +
                "\nSaldo: R$ " + p1.getSaldo();
        // Exibindo mensagem com os dados do cliente:
        JOptionPane.showMessageDialog(null, dados);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnEncerrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarContaActionPerformed
        // TODO add your handling code here:
        // Chamando método fechar conta:
        p1.fecharConta();
        
        if(p1.isStatus() == false) {
            // Remove texto do label do usuário:
            lblNomeCliente.setText("");
            
            // Remove icone do label de imagem:
            lblImagem.setIcon(null);

            // Se a conta foi fechada, desativa botões de operações bancárias:
            btnInfo.setEnabled(false);
            btnDeposito.setEnabled(false);
            btnSaque.setEnabled(false);
            btnPagarMensalidade.setEnabled(false);
            btnEncerrarConta.setEnabled(false);
        
            // Ativa botão de criar conta, caso a pessoa queira criar novamente:
            btnCriarConta.setEnabled(true);
        }
    }//GEN-LAST:event_btnEncerrarContaActionPerformed

    private void btnPagarMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMensalidadeActionPerformed
        // TODO add your handling code here:
        // Chamando método para pagar mensalidade:
        p1.pagarMensalidade();
    }//GEN-LAST:event_btnPagarMensalidadeActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        // Confirma saída do programa.
        int op;
        op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?");
        
        // Se sim, fecha o programa.
        if(op == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicioBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicioBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicioBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicioBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExercicioBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarConta;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnEncerrarConta;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnPagarMensalidade;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSaque;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSeparator sprLinha;
    // End of variables declaration//GEN-END:variables
}
