package exerciciotriangulo;

/**
 *
 * @author Lucas Bastos
 */
public class Triangulo extends javax.swing.JFrame {

    /**
     * Creates new form Triangulo
     */
    public Triangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        sprLinha = new javax.swing.JSeparator();
        lblSegA = new javax.swing.JLabel();
        lblSegB = new javax.swing.JLabel();
        lblSegC = new javax.swing.JLabel();
        sldSegA = new javax.swing.JSlider();
        sldSegB = new javax.swing.JSlider();
        sldSegC = new javax.swing.JSlider();
        lblSegAResult = new javax.swing.JLabel();
        lblSegBResult = new javax.swing.JLabel();
        lblSegCResult = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        lblTrianguloResult = new javax.swing.JLabel();
        lblTipoTriangulo = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfo.setText("Escolha o tamanho dos lados para o triângulo:");

        lblSegA.setText("Segmento A:");

        lblSegB.setText("Segmento B:");

        lblSegC.setText("Segmento C:");

        sldSegA.setMaximum(20);
        sldSegA.setValue(10);
        sldSegA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSegAStateChanged(evt);
            }
        });

        sldSegB.setMaximum(20);
        sldSegB.setValue(10);
        sldSegB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSegBStateChanged(evt);
            }
        });

        sldSegC.setMaximum(20);
        sldSegC.setValue(10);
        sldSegC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSegCStateChanged(evt);
            }
        });

        lblSegAResult.setText("10");

        lblSegBResult.setText("10");

        lblSegCResult.setText("10");

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        lblTrianguloResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTrianguloResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTipoTriangulo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTipoTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/triangulo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfo)
                            .addComponent(sprLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblSegB)
                                        .addGap(18, 18, 18)
                                        .addComponent(sldSegB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSegA)
                                        .addGap(18, 18, 18)
                                        .addComponent(sldSegA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSegAResult, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(lblSegBResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblSegC)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTipoTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldSegC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTrianguloResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSegCResult, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addComponent(sprLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSegA)
                            .addComponent(sldSegA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSegAResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSegB)
                            .addComponent(sldSegB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSegBResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSegC)
                            .addComponent(sldSegC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSegCResult, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblTrianguloResult, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldSegAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSegAStateChanged
        // TODO add your handling code here:
        // Pega o valor para A selecionado no slider, converte-o para string e exibe no label.
        lblSegAResult.setText(Integer.toString(sldSegA.getValue()));
    }//GEN-LAST:event_sldSegAStateChanged

    private void sldSegBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSegBStateChanged
        // TODO add your handling code here:
        // Pega o valor para B selecionado no slider, converte-o para string e exibe no label.
        lblSegBResult.setText(Integer.toString(sldSegB.getValue()));
    }//GEN-LAST:event_sldSegBStateChanged

    private void sldSegCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSegCStateChanged
        // TODO add your handling code here:
        // Pega o valor para C selecionado no slider, converte-o para string e exibe no label.
        lblSegCResult.setText(Integer.toString(sldSegC.getValue()));
    }//GEN-LAST:event_sldSegCStateChanged

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        // Cria as variáveis para guardar o tamanho dos lados obtidos nos sliders:
        int ladoA = sldSegA.getValue();
        int ladoB = sldSegB.getValue();
        int ladoC = sldSegC.getValue();
        boolean result; // Variável tipo boolean para verificação do triângulo.
        
        // Verifica se o tamanho dos lados possibilita a existência do triângulo:
        if (ladoA > Math.abs(ladoB-ladoC) && ladoA < (ladoB+ladoC)) {
            lblTrianguloResult.setText("Formam um triângulo!");
            result = true;
        } else if (ladoB > Math.abs(ladoA-ladoC) && ladoB < (ladoA+ladoC)) {
            lblTrianguloResult.setText("Formam um triângulo!");
            result = true;
        } else if (ladoC > Math.abs(ladoA-ladoB) && ladoC < (ladoA+ladoB)) {
            lblTrianguloResult.setText("Formam um triângulo!");
            result = true;
        } else {
            lblTrianguloResult.setText("NÃO é um triângulo!");
            result = false;
        }
        
        // Se for um triângulo, verifica que tipo é, e exibe no label o tipo:
        if (result == true) {
            if ((ladoA == ladoB) && (ladoB == ladoC)) {
                lblTipoTriangulo.setText("Tipo: Equilátero");
            } else if ((ladoA == ladoB && ladoB != ladoC) || (ladoB == ladoC && ladoC != ladoA) || (ladoC == ladoA && ladoA != ladoB)) {
                lblTipoTriangulo.setText("Tipo: Isósceles");
            } else if ((ladoA != ladoB) && (ladoB != ladoC))
                lblTipoTriangulo.setText("Tipo: Escaleno");
        } else {
            lblTipoTriangulo.setText("");
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblSegA;
    private javax.swing.JLabel lblSegAResult;
    private javax.swing.JLabel lblSegB;
    private javax.swing.JLabel lblSegBResult;
    private javax.swing.JLabel lblSegC;
    private javax.swing.JLabel lblSegCResult;
    private javax.swing.JLabel lblTipoTriangulo;
    private javax.swing.JLabel lblTrianguloResult;
    private javax.swing.JSlider sldSegA;
    private javax.swing.JSlider sldSegB;
    private javax.swing.JSlider sldSegC;
    private javax.swing.JSeparator sprLinha;
    // End of variables declaration//GEN-END:variables
}
